export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';

export const AUTH_UPDATE = 'AUTH_UPDATE';

export const AUTH_EXPIRE = 'AUTH_EXPIRE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const PROPERTY_FETCH_REQUEST = 'PROPERTY_FETCH_REQUEST';

export const PROPERTY_FETCH_SUCCESS = 'PROPERTY_FETCH_SUCCESS';

export const PROPERTY_FETCH_FAILURE = 'PROPERTY_FETCH_FAILURE';